version: "3.8"

services:
    php-testing-workshop-php:
        build:
           context: ./
           dockerfile: docker/php/Dockerfile
        ports:
            - 8800:80
        volumes:
            -   ./:/var/www/app
    php-testing-workshop-mysql:
        image: mysql:8
        platform: linux/x86_64
        ports:
            - 3360:3306
        volumes:
            - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=testing-workshop
